[package]
name = "parser-parser"
version = "0.1.0"
authors = ["Karol Belina <karolbelina@gmail.com>"]
edition = "2018"

[dependencies]
structopt = "0.3.12"
base = { path = "../base" }
ebnf = { path = "../ebnf" }
